# Generated by Django 4.1.5 on 2023-02-18 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPeliseries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posteos',
            name='body',
            field=models.TextField(default=0),
        ),
    ]
