# Generated by Django 4.1.5 on 2023-02-18 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppPeliseries', '0002_posteos_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=40)),
                ('genero', models.CharField(max_length=30)),
                ('body', models.TextField(default='')),
                ('autor', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('director', models.CharField(max_length=50)),
                ('fechaestreno', models.DateField()),
                ('pais', models.CharField(max_length=40)),
                ('duracion', models.IntegerField()),
                ('genero1', models.CharField(max_length=30)),
                ('genero2', models.CharField(max_length=30)),
                ('body', models.TextField(default='')),
                ('autor', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('director', models.CharField(max_length=50)),
                ('fechaestreno', models.DateField()),
                ('cantepisodios', models.IntegerField()),
                ('genero1', models.CharField(max_length=30)),
                ('genero2', models.CharField(max_length=30)),
                ('body', models.TextField(default='')),
                ('autor', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Posteos',
        ),
    ]
