# Generated by Django 4.1.5 on 2023-02-19 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPeliseries', '0003_musica_pelicula_serie_delete_posteos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='director',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='fechaestreno',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='pais',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='añoestreno',
            field=models.IntegerField(default=0),
        ),
    ]
