# Generated by Django 4.1.5 on 2023-02-20 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPeliseries', '0004_remove_pelicula_director_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musica',
            name='autor',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='autor',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='serie',
            name='autor',
            field=models.CharField(default='', max_length=50),
        ),
    ]
