# Generated by Django 4.1.5 on 2023-02-20 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppPeliseries', '0006_remove_serie_director_remove_serie_fechaestreno_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pelicula',
            old_name='genero1',
            new_name='genero',
        ),
        migrations.RenameField(
            model_name='serie',
            old_name='genero1',
            new_name='genero',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='genero2',
        ),
    ]
