# Generated by Django 4.1.5 on 2023-02-22 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPeliseries', '0007_rename_genero1_pelicula_genero_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='duracion',
        ),
        migrations.AddField(
            model_name='serie',
            name='temporadas',
            field=models.IntegerField(default=1),
        ),
    ]
