# Generated by Django 4.1.5 on 2023-02-22 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPeliseries', '0008_remove_pelicula_duracion_serie_temporadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
