# Generated by Django 4.1.5 on 2023-02-22 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPeliseries', '0009_pelicula_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musica',
            old_name='body',
            new_name='reseña',
        ),
        migrations.RenameField(
            model_name='pelicula',
            old_name='body',
            new_name='reseña',
        ),
        migrations.RenameField(
            model_name='serie',
            old_name='body',
            new_name='reseña',
        ),
        migrations.AddField(
            model_name='musica',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/musica/'),
        ),
        migrations.AddField(
            model_name='serie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/series/'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='añoestreno',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/pelis/'),
        ),
    ]
